/**
* SSP-Online Backend
* This is a the backend for the SSP Online Game. It is a RESTful API that is used by the frontend to play the game.  Some useful links: - [ssp-online](https://github.com/doofmars/ssp-online) - The source code for the SSP Online Game - [ssp-backend](https://github.com/doofmars/ssp-backend) - The source code for the SSP Backend
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.doofmars.ssp.backend.models

import de.doofmars.ssp.backend.models.Pawn

import java.io.Serializable
/**
 * 
 * @param width 
 * @param height 
 * @param grid 
 */
data class Board(
    val width: kotlin.Long,
    val height: kotlin.Long,
    val grid: kotlin.collections.List<kotlin.collections.List<Pawn>>
) : Serializable 
{
    companion object {
        private const val serialVersionUID: Long = 123
    }
}

