/**
* SSP-Online Backend
* This is a the backend for the SSP Online Game. It is a RESTful API that is used by the frontend to play the game.  Some useful links: - [ssp-online](https://github.com/doofmars/ssp-online) - The source code for the SSP Online Game - [ssp-backend](https://github.com/doofmars/ssp-backend) - The source code for the SSP Backend
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.doofmars.ssp.backend.models

import de.doofmars.ssp.backend.models.Board
import de.doofmars.ssp.backend.models.GameStatus
import de.doofmars.ssp.backend.models.Player

/**
 * 
 * @param id 
 * @param host 
 * @param guest 
 * @param currentRound 
 * @param winner 
 * @param board 
 * @param status 
 * @param lastUpdate 
 */
data class Game(
    val id: kotlin.String,
    val host: Player,
    val guest: Player,
    val currentRound: kotlin.Long,
    val winner: Game.Winner,
    val board: Board? = null,
    val status: GameStatus? = null,
    val lastUpdate: java.time.OffsetDateTime? = null
) 
{
    /**
    * 
    * Values: nONE,hOST,gUEST,dRAW
    */
    enum class Winner(val value: kotlin.String){
        nONE("NONE"),
        hOST("HOST"),
        gUEST("GUEST"),
        dRAW("DRAW");
    }
}

