/**
* SSP-Online Backend
* This is a the backend for the SSP Online Game. It is a RESTful API that is used by the frontend to play the game.  Some useful links: - [ssp-online](https://github.com/doofmars/ssp-online) - The source code for the SSP Online Game - [ssp-backend](https://github.com/doofmars/ssp-backend) - The source code for the SSP Backend
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.doofmars.ssp.backend.models


/**
* 
* Values: wAITINGFORGUEST,sETUPPLACEFLAG,sETUPPLACETRAP,sETUPSHUFFLEPAWNS,rUNNINGPLAYERTURN,rUNNINGOPPONENTTURN,rUNNINGFIGHT,rUNNINGSAMEWEAPON,fINISHEDHOSTWIN,fINISHEDGUESTWIN,fINISHEDDRAW
*/
enum class GameStatus(val value: kotlin.String) {

    wAITINGFORGUEST("WAITING_FOR_GUEST"),

    sETUPPLACEFLAG("SETUP_PLACE_FLAG"),

    sETUPPLACETRAP("SETUP_PLACE_TRAP"),

    sETUPSHUFFLEPAWNS("SETUP_SHUFFLE_PAWNS"),

    rUNNINGPLAYERTURN("RUNNING_PLAYER_TURN"),

    rUNNINGOPPONENTTURN("RUNNING_OPPONENT_TURN"),

    rUNNINGFIGHT("RUNNING_FIGHT"),

    rUNNINGSAMEWEAPON("RUNNING_SAME_WEAPON"),

    fINISHEDHOSTWIN("FINISHED_HOST_WIN"),

    fINISHEDGUESTWIN("FINISHED_GUEST_WIN"),

    fINISHEDDRAW("FINISHED_DRAW");

}

