/**
 * SSP-Online Backend
 * This is a the backend for the SSP Online Game. It is a RESTful API that is used by the frontend to play the game.  Some useful links: - [ssp-online](https://github.com/doofmars/ssp-online) - The source code for the SSP Online Game - [ssp-backend](https://github.com/doofmars/ssp-backend) - The source code for the SSP Backend
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.doofmars.ssp.backend.models

import kotlinx.serialization.Serializable

/**
 *
 * @param item
 * @param owner
 */
@Serializable
data class Pawn(
    val item: Pawn.Item,
    val owner: Pawn.Owner
) {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     *
     * Values: ROCK,PAPER,SCISSORS,TRAP,FLAG,EMPTY
     */
    enum class Item(val value: kotlin.String) {
        ROCK("ROCK"),
        PAPER("PAPER"),
        SCISSORS("SCISSORS"),
        TRAP("TRAP"),
        FLAG("FLAG"),
        EMPTY("EMPTY");
    }

    /**
     *
     * Values: HOST,GUEST
     */
    enum class Owner(val value: kotlin.String) {
        HOST("HOST"),
        GUEST("GUEST");
    }
}

