/**
 * SSP-Online Backend
 * This is a the backend for the SSP Online Game. It is a RESTful API that is used by the frontend to play the game.  Some useful links: - [ssp-online](https://github.com/doofmars/ssp-online) - The source code for the SSP Online Game - [ssp-backend](https://github.com/doofmars/ssp-backend) - The source code for the SSP Backend
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.doofmars.ssp.backend.models

import kotlinx.serialization.Serializable


/**
 *
 * @param name
 * @param id
 * @param key Identify the player against the server
 */
@Serializable
data class Player(
    val name: kotlin.String,
    val id: kotlin.Long? = null,
    /* Identify the player against the server */
    val key: kotlin.String? = null
) {
    companion object {
        private const val serialVersionUID: Long = 123
    }
}

