version: '3'
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        expose:
            - "27017"
    #    volumes:
    #      - mongodb_data_container:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        expose:
            - "8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: example
            ME_CONFIG_SITE_BASEURL: /express
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        depends_on:
            - mongo

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - "8080"
        environment:
            DB_HOST: mongo
            DB_USERNAME: root
            DB_PASSWORD: example
        depends_on:
            - mongo

    admin-frontend:
        build:
            context: ./admin-frontend
            dockerfile: Dockerfile
        expose:
            - "80"
        environment:
            REACT_APP_API_URL: http://backend:8080
        depends_on:
            - backend

    # nginx-reverse-proxy this will be used to solve issues of cross origin requests from the admin-frontend to the backend
    reverse-proxy:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./nginx-reverse_proxy.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend
            - admin-frontend
volumes:
    mongodb_data_container:
