from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.pawn import Pawn
from openapi_server.models.player import Player
from openapi_server import util

from openapi_server.models.pawn import Pawn  # noqa: E501
from openapi_server.models.player import Player  # noqa: E501

class GameGameIdTurnPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, player=None, pawn=None, pos_x=None, pos_y=None, action=None):  # noqa: E501
        """GameGameIdTurnPostRequest - a model defined in OpenAPI

        :param player: The player of this GameGameIdTurnPostRequest.  # noqa: E501
        :type player: Player
        :param pawn: The pawn of this GameGameIdTurnPostRequest.  # noqa: E501
        :type pawn: Pawn
        :param pos_x: The pos_x of this GameGameIdTurnPostRequest.  # noqa: E501
        :type pos_x: int
        :param pos_y: The pos_y of this GameGameIdTurnPostRequest.  # noqa: E501
        :type pos_y: int
        :param action: The action of this GameGameIdTurnPostRequest.  # noqa: E501
        :type action: str
        """
        self.openapi_types = {
            'player': Player,
            'pawn': Pawn,
            'pos_x': int,
            'pos_y': int,
            'action': str
        }

        self.attribute_map = {
            'player': 'player',
            'pawn': 'pawn',
            'pos_x': 'pos-x',
            'pos_y': 'pos-y',
            'action': 'action'
        }

        self._player = player
        self._pawn = pawn
        self._pos_x = pos_x
        self._pos_y = pos_y
        self._action = action

    @classmethod
    def from_dict(cls, dikt) -> 'GameGameIdTurnPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _game__gameId__turn_post_request of this GameGameIdTurnPostRequest.  # noqa: E501
        :rtype: GameGameIdTurnPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def player(self) -> Player:
        """Gets the player of this GameGameIdTurnPostRequest.


        :return: The player of this GameGameIdTurnPostRequest.
        :rtype: Player
        """
        return self._player

    @player.setter
    def player(self, player: Player):
        """Sets the player of this GameGameIdTurnPostRequest.


        :param player: The player of this GameGameIdTurnPostRequest.
        :type player: Player
        """
        if player is None:
            raise ValueError("Invalid value for `player`, must not be `None`")  # noqa: E501

        self._player = player

    @property
    def pawn(self) -> Pawn:
        """Gets the pawn of this GameGameIdTurnPostRequest.


        :return: The pawn of this GameGameIdTurnPostRequest.
        :rtype: Pawn
        """
        return self._pawn

    @pawn.setter
    def pawn(self, pawn: Pawn):
        """Sets the pawn of this GameGameIdTurnPostRequest.


        :param pawn: The pawn of this GameGameIdTurnPostRequest.
        :type pawn: Pawn
        """
        if pawn is None:
            raise ValueError("Invalid value for `pawn`, must not be `None`")  # noqa: E501

        self._pawn = pawn

    @property
    def pos_x(self) -> int:
        """Gets the pos_x of this GameGameIdTurnPostRequest.


        :return: The pos_x of this GameGameIdTurnPostRequest.
        :rtype: int
        """
        return self._pos_x

    @pos_x.setter
    def pos_x(self, pos_x: int):
        """Sets the pos_x of this GameGameIdTurnPostRequest.


        :param pos_x: The pos_x of this GameGameIdTurnPostRequest.
        :type pos_x: int
        """
        if pos_x is None:
            raise ValueError("Invalid value for `pos_x`, must not be `None`")  # noqa: E501

        self._pos_x = pos_x

    @property
    def pos_y(self) -> int:
        """Gets the pos_y of this GameGameIdTurnPostRequest.


        :return: The pos_y of this GameGameIdTurnPostRequest.
        :rtype: int
        """
        return self._pos_y

    @pos_y.setter
    def pos_y(self, pos_y: int):
        """Sets the pos_y of this GameGameIdTurnPostRequest.


        :param pos_y: The pos_y of this GameGameIdTurnPostRequest.
        :type pos_y: int
        """
        if pos_y is None:
            raise ValueError("Invalid value for `pos_y`, must not be `None`")  # noqa: E501

        self._pos_y = pos_y

    @property
    def action(self) -> str:
        """Gets the action of this GameGameIdTurnPostRequest.


        :return: The action of this GameGameIdTurnPostRequest.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action: str):
        """Sets the action of this GameGameIdTurnPostRequest.


        :param action: The action of this GameGameIdTurnPostRequest.
        :type action: str
        """
        allowed_values = ["MOVE_X-1", "MOVE_X+1", "MOVE_Y-1", "MOVE_Y+1", "PLACE_TRAP", "PLACE_FLAG", "SHUFFLE_PAWNS"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"
                .format(action, allowed_values)
            )

        self._action = action
